version: '3.1'

services:
  db:
    container_name: database
    image: postgres:14.1-alpine
    env_file:
      - ".env"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    working_dir: "/src/"
    command: python3 app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db
  django_migration:
    container_name: migrations
    build:
      context: .
    working_dir: "/src/"
    command: sh -c "python3 django_app.py makemigrations && python3 django_app.py migrate"
    networks:
      - botnet
    restart: "no"
    depends_on:
      - db
    volumes:
      - .:/src

networks:
  botnet:
    driver: bridge
