version: '3.1'

services:
  # Если хотите подключить базу данных
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
      env_file:
        - ".env"
    environment:
      PG_PASSWORD: $DB_PASS
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

# указываются используемые сети
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge
