# Generated by Django 3.1.13 on 2021-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='ID пользователя Телеграм')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=255, verbose_name='Username Telegram')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('commentary', models.TextField(max_length=300, null=True, verbose_name='About the user')),
                ('photo', models.CharField(max_length=200, verbose_name='Фото file_id')),
            ],
            options={
                'verbose_name': ('Пользователь',),
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
